export const CHARACTER_PRESETS = {
  pm: {
    id: "pm",
    label: "PM",
    name: "PM",
    subtitle: "Lotus Swirl",
    color: "#ffffff",
    vestColor: "#1565c0",
    weapon: "Lotus",
    attackRadius: 72,
    attackCooldown: 0.5,
    maxStamina: 100,
    speed: 210,
    width: 48,
    height: 72,
    facingDefault: 1,
  },
  pappu: {
    id: "pappu",
    label: "PAPPU",
    name: "PAPPU",
    subtitle: "Big Hand Slap AoE",
    color: "#ffffff",
    vestColor: "#5d4037",
    weapon: "Big Hand",
    attackRadius: 65,
    attackCooldown: 0.32,
    maxStamina: 100,
    speed: 240,
    width: 46,
    height: 70,
    facingDefault: 1,
  },
};
